---
title: "Descriptions of Graphs"
output: html_document
date: '2022-04-16'
---

```library(igraph)

library(ggraph)
set.seed(2017)

ggraph(bigram_graph, layout = "fr") +
  geom_edge_link() +
  geom_node_point() +
  geom_node_text(aes(label = name), vjust = 1, hjust = 1)
```

## Earlier graphs till this point were completed

The above code was executed for the Visualization of Bigrams with the ggraph library.
This graph depicts the relationships among the words at the same time.The words can be arranged in a visual of a network, like showcasing all the connected nodes.

This graph has three variables:

<b>from</b>: the node an edge is coming from.  
<b>to</b>: the node and edge is going to.
<b>weight:</b> This is a like a score given to each edge

This library has many options to portray and in analyzing the networks and making changes.
In this graph we can actually visualize some details of the text structure like salutations etc

```set.seed(2020)

a <- grid::arrow(type = "closed", length = unit(.15, "inches"))

ggraph(bigram_graph, layout = "fr") +
  geom_edge_link(aes(edge_alpha = n), show.legend = FALSE,
                 arrow = a, end_cap = circle(.07, 'inches')) +
  geom_node_point(color = "lightblue", size = 5) +
  geom_node_text(aes(label = name), vjust = 1, hjust = 1) +
  theme_void()

```

## 

In this graph we change the options to the node layer to make the nodes more attractive.
We also add a theme that's useful for plotting networks, <b>theme_void()</b>


```
count_bigrams <- function(dataset) {
  dataset %>%
    unnest_tokens(bigram, text, token = "ngrams", n = 2) %>%
    separate(bigram, c("word1", "word2"), sep = " ") %>%
    filter(!word1 %in% stop_words$word,
           !word2 %in% stop_words$word) %>%
    count(word1, word2, sort = TRUE)
}

visualize_bigrams <- function(bigrams) {
  set.seed(2016)
  a <- grid::arrow(type = "closed", length = unit(.15, "inches"))
  
  bigrams %>%
    graph_from_data_frame() %>%
    ggraph(layout = "fr") +
    geom_edge_link(aes(edge_alpha = n), show.legend = FALSE, arrow = a) +
    geom_node_point(color = "lightblue", size = 5) +
    geom_node_text(aes(label = name), vjust = 1, hjust = 1) +
    theme_void()
}


```
This code above showcases 

```
library(stringr)

kjv_bigrams <- kjv %>%
  count_bigrams()

# filter out rare combinations, as well as digits
kjv_bigrams %>%
  filter(n > 40,
         !str_detect(word1, "\\d"),
         !str_detect(word2, "\\d")) %>%
  visualize_bigrams()
```


In this code for the above graph we see that this plot shows the terms used in Bible like "thou" and "thy".
The visualize_bigrams functions can be used from the guthernberg package.

